---
name: 'ops-manager'
provider: vsphere
version: 1.5.5.0 #~~~~!!!
opts:
  ip: 1.2.3.4
  username: foo
  password: bar
  ova_path: ops-manager.ova
  portgroup: 'dummy-portgroup'
  netmask: '255.255.255.0'
  gateway: '1.2.3.1'
  dns: '8.8.8.8'
  datastore: 'DS1'
  vcenter:
    username: VM_VCENTER_USER
    password: VM_VCENTER_PASSWORD
    host: 1.2.3.2
    datacenter: VM_DATACENTER
    cluster: VM_CLUSTER
  ntp_servers:
  - clock1.example.com
  - clock2.example.com
