---
name: 'ops-manager'

provider: vsphere
desired_version: 1.4.11.0
ip: 1.2.3.4
username: foo
password: bar
pivnet_token: abc123
opts:
  ova_path: ops-manager.ova # you can also specify the path with *. e.g.: ops-manager-ova/*.ova. This is usefull when using concourse and the pivnet-resource
  portgroup: 'dummy-portgroup'
  netmask: '255.255.255.0'
  gateway: '1.2.3.1'
  dns: '8.8.8.8'
  datastore: 'DS1'
  vcenter:
    username: VM_VCENTER_USER
    password: VM_VCENTER_PASSWORD
    host: 1.2.3.2
    datacenter: VM_DATACENTER
    cluster: VM_CLUSTER
  ntp_servers:
  - clock1.example.com
  - clock2.example.com
